#!/usr/bin/env bash
# Run a demo of the Rapid ZTP app.
#
# Copyright (c) 2019 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.0 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."

script/setup

docker-compose up --build --force-recreate --detach

echo "Waiting for services to start..."
sleep 5

pipenv run examples/example.py

echo "Don't forget shutdown the server services when you are done demoing the app. Just run:"
echo ""
echo "    $ script/server down"
